### ISSUE TITLE
More than one csvs downloaded contains the same data

### ISSUE THREAD

**Issue by Pl0414141** [wrighter/ib-scripts#2]
Hi,

i have executed the following command:

python3.8 download_bars.py --size "30 secs" --security-type CONTFUT --max-days --exchange GLOBEX NQ

Now, in the path /ib-scripts/src/data/CONTFUT/30_secs/NQ i can see a lot of CSVs but some CSVs contains the same data

Example: 20220904.csv

date,open,high,low,close,volume,barCount,wap
20220905  00:00:00,12110.5,12131.0,12104.75,12112.0,332,241,12115.5
20220905  00:00:30,12111.25,12114.5,12106.5,12107.5,119,76,12110.375

Example: 220220905.csv

date,open,high,low,close,volume,barCount,wap
20220905  00:00:00,12110.5,12131.0,12104.75,12112.0,332,241,12115.5
20220905  00:00:30,12111.25,12114.5,12106.5,12107.5,119,76,12110.375

**Comment by wrighter** [comment]
This should be fixed by #6
