### ISSUE TITLE
Column 'date' with DateTime format

### ISSUE THREAD

**Issue by Pl0414141** [wrighter/ib-scripts#3]
Hello,

mostly parsers do not understand the following syntax of 'date' due do not have DateTime format in the CSV content:

date
20220128  00:00:00

I suggest convert to the following:

date
2022.01.28 00:00:00

**Comment by wrighter** [comment]
I've never used that format before, but it seems reasonable to make the date format an option since users may have different preferences.

**Comment by wrighter** [comment]
This is resolved in #16
