### ISSUE TITLE
ValueError: time data '20210419' does not match format '%Y-%m-%d %H:%M:%S%z

### ISSUE THREAD

**Issue by n-e-o-o** [wrighter/ib-scripts#7]
Hi Matt,

Appears a few users are experiencing the same issue so thought to log an issue for it. Applies to your examples listed in the Article and many other attempts at getting this working.

I am using API Build 10.20.1g, Jan 3, 2023 4:39:22 PM.

Regards,
Milan

**Comment by wrighter** [comment]
I have reproduced the error message, but not sure if it's exactly what you're seeing. I think this is affecting daily bars during the bar writing process.

So for example, this work:

`./src/download_bars.py --size '1 hour' AAPL`

But this doesn't

`./src/download_bars.py --size '1 day' AAPL`

**Comment by n-e-o-o** [comment]
Correct, i am trying to collect daily bars.
